name: Reclutamiento de Agente
on: 
    workflow_dispatch:

jobs:
    reporte-de-reclutamiento:
        runs-on: ubuntu-latest

        steps:
            - name: El agente se presenta
              run: echo "Hola, soy el nuevo agente." 

            - name: Reporte de identidad
              run: |
                echo "Reporte de identidad"
                echo "===================="
                echo "Nombre: ${{ github.actor }}"
                echo "Fecha de ingreso: $(date)"
                echo "Contexto de GitHub"
                echo "Repositorio: ${{ github.repository }}"
                echo "Operación: ${{ github.sha }}"
                echo "Metadata: ${{ toJSON(github) }}"
                echo "===================="

            - name: Capacidades del agente
              run: |
                echo "Capacidades del agente"
                echo "===================="
                echo "Sistema operativo"
                uname -a
                echo "Habilidades técnicas."
                node --version
                git --version
                python3 --version

            - name: Reconocimiento del terreno
              run: |
                echo "Reconocimiento del terreno"
                echo "===================="
                echo "Listando archivos en el directorio actual:"
                ls -la
                echo "Mostrando el espacio en disco:"
                df -h
                echo "===================="

                
              


