name: 🌋Acceso a la fortaleza
on: 
    workflow_dispatch:

jobs:
    acceso-a-la-fortaleza:
        runs-on: ubuntu-latest

        steps:
            - name: El agente llega a la fortaleza
              run: |
                echo "El agente ${{ github.actor }} ha llegado a la fortaleza."
                echo ""
                echo "Busca los archivos de la legión"
                ls -la
                echo ""
                echo "❌ qué pasó? No hay nada aquí."

            - name: "Braniac desbloquea la caja fuerte"
              uses: actions/checkout@v4

            - name: "Ahora sí, manos a ver los planes"
              run: |
                echo "Buscar los archivos de la legión"
                ls -la
                echo "✅ Ahora sí, funciona!!"
                echo ""
                echo "Planes:"
                ls planes/
                echo "Villanos"
                ls miembros/
                echo "Inteligencia"
                ls inteligencia/
                